# generated by matugen template
PRIMARY_HEX="{{colors.primary.default.hex_stripped}}"

# prompt uses 24-bit color
export PS1="\[\e[38;2;$((16#${PRIMARY_HEX:0:2}));$((16#${PRIMARY_HEX:2:2}));$((16#${PRIMARY_HEX:4:2}))m\][\h][\w]\$ \[\e[0m\]"
